// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkw-OnW6CK5HNaZEUGeRrW1ox7vFQbuRI',
    appId: '1:798061984645:web:04677b08313047b17122ec',
    messagingSenderId: '798061984645',
    projectId: 'fitbot-2fa67',
    authDomain: 'fitbot-2fa67.firebaseapp.com',
    storageBucket: 'fitbot-2fa67.firebasestorage.app',
    measurementId: 'G-7JVZVBSLKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaiCYI7L73ZdrCKNFQKaLngGzGYmqKWUk',
    appId: '1:798061984645:android:b9cd2ba96016f1117122ec',
    messagingSenderId: '798061984645',
    projectId: 'fitbot-2fa67',
    storageBucket: 'fitbot-2fa67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQR-uE9MP4m6Vu9cBY0NdpfA-F8bv6hKc',
    appId: '1:798061984645:ios:64d33e895e818e897122ec',
    messagingSenderId: '798061984645',
    projectId: 'fitbot-2fa67',
    storageBucket: 'fitbot-2fa67.firebasestorage.app',
    iosBundleId: 'com.example.fitbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQR-uE9MP4m6Vu9cBY0NdpfA-F8bv6hKc',
    appId: '1:798061984645:ios:64d33e895e818e897122ec',
    messagingSenderId: '798061984645',
    projectId: 'fitbot-2fa67',
    storageBucket: 'fitbot-2fa67.firebasestorage.app',
    iosBundleId: 'com.example.fitbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkw-OnW6CK5HNaZEUGeRrW1ox7vFQbuRI',
    appId: '1:798061984645:web:29b7d9e734db96fe7122ec',
    messagingSenderId: '798061984645',
    projectId: 'fitbot-2fa67',
    authDomain: 'fitbot-2fa67.firebaseapp.com',
    storageBucket: 'fitbot-2fa67.firebasestorage.app',
    measurementId: 'G-KCP4QWWX54',
  );
}

